2024-11-22 15:44:43,988 - INFO - 训练样本分布: target
0.0    436
1.0    218
Name: count, dtype: int64
2024-11-22 15:44:44,024 - INFO - 连续特征已标准化
2024-11-22 15:44:44,030 - INFO - 预处理后的 result_array 形状: (654, 10, 4)
2024-11-22 15:44:44,057 - INFO - 连续特征已标准化
2024-11-22 15:44:44,062 - INFO - 预处理后的 result_array 形状: (720, 10, 4)
2024-11-22 15:44:44,084 - INFO - 连续特征已标准化
2024-11-22 15:44:44,089 - INFO - 预处理后的 result_array 形状: (776, 10, 4)
2024-11-22 15:44:44,152 - INFO - 连续特征已标准化
2024-11-22 15:44:44,187 - INFO - 预处理后的 result_array 形状: (654, 15, 17)
2024-11-22 15:44:44,298 - INFO - 连续特征已标准化
2024-11-22 15:44:44,332 - INFO - 预处理后的 result_array 形状: (720, 15, 17)
2024-11-22 15:44:44,399 - INFO - 连续特征已标准化
2024-11-22 15:44:44,434 - INFO - 预处理后的 result_array 形状: (776, 15, 17)
2024-11-22 15:44:44,450 - INFO - 连续特征已标准化
2024-11-22 15:44:44,458 - INFO - 预处理后的 result_array 形状: (654, 5, 9)
2024-11-22 15:44:44,476 - INFO - 连续特征已标准化
2024-11-22 15:44:44,484 - INFO - 预处理后的 result_array 形状: (720, 5, 9)
2024-11-22 15:44:44,503 - INFO - 连续特征已标准化
2024-11-22 15:44:44,512 - INFO - 预处理后的 result_array 形状: (776, 5, 9)
2024-11-22 15:44:44,629 - INFO - 数据加载时间: 11.038000583648682秒
2024-11-22 15:44:44,629 - INFO - 训练数据形状: (654, 10, 4)
2024-11-22 15:44:56,279 - ERROR - Input contains NaN.
Traceback (most recent call last):
  File "C:\Users\chao_ma02\Desktop\work\ts2vec\user_embedding.py", line 284, in <module>
    encode_and_evaluate(model_diaoyong, diaoyong_features_train, diaoyong_features_test, diaoyong_features_oot, labels_train, labels_test, labels_oot, "diaoyong")
  File "C:\Users\chao_ma02\Desktop\work\ts2vec\user_embedding.py", line 231, in encode_and_evaluate
    eval_metrics_train = eval_classification(train_score, labels_train)
  File "C:\Users\chao_ma02\Desktop\work\ts2vec\tasks\classification.py", line 25, in eval_classification
    auprc = average_precision_score(test_labels_onehot, score)
  File "d:\Users\chao_ma02\AppData\Local\anaconda3\envs\normal\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "d:\Users\chao_ma02\AppData\Local\anaconda3\envs\normal\lib\site-packages\sklearn\metrics\_ranking.py", line 268, in average_precision_score
    return _average_binary_score(
  File "d:\Users\chao_ma02\AppData\Local\anaconda3\envs\normal\lib\site-packages\sklearn\metrics\_base.py", line 80, in _average_binary_score
    y_score = check_array(y_score)
  File "d:\Users\chao_ma02\AppData\Local\anaconda3\envs\normal\lib\site-packages\sklearn\utils\validation.py", line 1064, in check_array
    _assert_all_finite(
  File "d:\Users\chao_ma02\AppData\Local\anaconda3\envs\normal\lib\site-packages\sklearn\utils\validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "d:\Users\chao_ma02\AppData\Local\anaconda3\envs\normal\lib\site-packages\sklearn\utils\validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.
